version: '3.8'

services:
  nexus-app:
    build: .
    container_name: nexus-app
    volumes:
      - .:/var/www/html
    depends_on:
      - nexus-db
    environment:
      - DB_HOST=nexus-db
      - DB_PORT=3306
      - DB_DATABASE=nexus_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nexus-db:
    image: mysql:8.0
    container_name: nexus-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexus_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  nexus-nginx:
    image: nginx:latest
    container_name: nexus-nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nexus-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nexus-phpmyadmin
    restart: always
    depends_on:
      - nexus-db
    environment:
      PMA_HOST: nexus-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
